#!/bin/bash
#declare -A filenames

export LC_ALL=C

is_uint() {
  case $1 in
    ''|*[!0-9]*)
      return 1
      ;;
  esac
}

if [ "$#" -lt 1 ]; then
  echo "Usage: $0 [-B <lines_before>] [-A <lines_after>] [-C <lines_before_and_after>] [-n] [-N] <filename(s)>"
  exit 1
fi

no_files=0
no_lines=0
def_lines_before=0
def_lines_after=0

while [ "$#" -gt 0 ]; do
  case $1 in
    -B*)
      lines_before="${1#-B}"
      lines_before="${lines_before#=}"
      if [ -z "$lines_before" ] && [ -n "$2" ]; then
        lines_before="$2"
        shift
      fi
      if ! is_uint "$lines_before"; then
        echo "Invalid -B option: $lines_before" >&2
        exit 1
      fi

      ;;
    -A*)
      lines_after="${1#-A}"
      lines_after="${lines_after#=}"
      if [ -z "$lines_after" ] && [ -n "$2" ]; then
        lines_after="$2"
        shift
      fi

      if ! is_uint "$lines_after"; then
        echo "Invalid -A option: $lines_after" >&2
        exit 1
      fi
      ;;
    -C*)
      lines_before="${1#-C}"
      lines_before="${lines_before#=}"
      if [ -z "$lines_before" ] && [ -n "$2" ]; then
        lines_before="$2"
        shift
      fi
      lines_after="$lines_before"
      if ! is_uint "$lines_after"; then
        echo "Invalid -C option: $lines_after" >&2
        exit 1
      fi
      ;;
    -n)
      no_lines=1
      ;;
    -N)
      no_files=1
      ;;
    *)
      if [[ ! "$1" =~ ^-.* ]]; then
        filenames+=("$(readlink -f -- "$1")") #["$1"]=1
      else
        echo "Invalid option: $1" >&2
        exit 1
      fi
      ;;
  esac
  shift
done

lines_before="${lines_before:-$def_lines_before}"
lines_after="${lines_after:-$def_lines_after}"

num_files="${#filenames[@]}"

if [ "$num_files" -eq 0 ]; then
  echo "No file(s) specified." >&2
  exit 1
fi

for filename in "${filenames[@]}"; do
  if ! [ -f "$filename" ] || ! [ -r "$filename" ]; then
#    echo "File does not exist: $filename" >&2
    continue
  fi

  line_count=$(wc -l < "$filename" 2>/dev/null)

  if [ "$line_count" -lt 1 ]; then
#    echo "File is empty: $filename" >&2
    continue
  fi

  middle_line=$((line_count / 2)) # XXX: Rounds down

  start_line=$((middle_line - lines_before))
  end_line=$((middle_line + lines_after))

  [ "$start_line" -le 0 ] && start_line=1
  [ "$end_line" -gt $line_count ] && end_line=$line_count

  if [ "$no_lines" -eq 1 ]; then
    if [ "$no_files" -eq 1 ]; then
      [ "$num_files" -ne 1 ] && sed -n "$start_line,${end_line}p" "$filename"  && continue
    else
      [ "$num_files" -ne 1 ] && sed -n "$start_line,${end_line}p" "$filename" | sed "s|^|$filename:|" && continue
    fi

    sed -n "$start_line,${end_line}p" "$filename"
  else
    if [ "$no_files" -eq 1 ]; then
      [ "$num_files" -ne 1 ] && sed "$start_line,$end_line"'!d;=' "$filename" | sed 'N;s/\n/:/' && continue
    else
      [ "$num_files" -ne 1 ] && sed "$start_line,$end_line"'!d;=' "$filename" | sed 'N;s/\n/:/' | sed "s|^|$filename:|" && continue
    fi

    sed "$start_line,$end_line"'!d;=' "$filename" | sed 'N;s/\n/:/'
  fi

done
